Repository fac-13/stackMatch, pull requests merged in 2018-05, with the labels that each got.

#13 Dev setup
  .eslintrc.json
  .gitignore
  package-lock.json
  package.json
  src/app.js
  src/controller/index.js
  src/index.js
  src/model/database/db_build.js
  src/model/database/db_build.sql
  src/model/database/db_build_test.js
  src/model/database/db_build_test.sql
  src/model/database/db_connection.js
  src/test/app.test.js
  src/test/db.test.js
  src/view/home.hbs
Labels: awaiting-merge

#45 Travis setup
  .travis.yml
  package-lock.json
  src/model/database/db_build_test.sql
  src/model/database/db_connection.js
Labels: awaiting-merge

#46 add home and static routes, add basic homepage
  package-lock.json
  public/css/style.css
  public/index.html
  src/app.js
  src/controller/index.js
  src/model/database/db_build.sql
  src/model/database/db_build_test.sql
  src/test/app.test.js
Labels: awaiting-merge

#49 set up handlebars and modularise home route
  package-lock.json
  package.json
  src/app.js
  src/controllers/home.js
  src/controllers/index.js
  src/view/home.hbs
  src/views/home.hbs
  src/views/layouts/main.hbs
Labels: awaiting-merge

#53 Add database build sql based on database schema
  package-lock.json
  src/model/database/db_build.sql
  src/model/database/db_build_test.sql
  src/test/db.test.js
Labels: awaiting-merge

#52 turn off no-console rule in eslint and apply linting
  .eslintrc.json
  src/controllers/home.js
  src/model/database/db_connection.js
Labels: awaiting-merge

#54 Setup outh2
  .gitignore
  package-lock.json
  package.json
  public/dom/home.js
  src/app.js
  src/controllers/auth.js
  src/controllers/index.js
  src/controllers/signup.js
  src/model/database/db_build.js
  src/oauth.js
  src/test/app.test.js
  src/test/db.test.js
  src/views/home.hbs
Labels: awaiting-merge

#55 Change database to include github avatar url
  src/model/database/db_build.sql
  src/model/database/db_build_test.sql
Labels: awaiting-merge

#58 query to get member data from database [WIP]
  src/model/queries/getMemberData.js
  src/test/db.test.js
Labels: awaiting-merge

#60 Passport setup
  src/app.js
  src/model/database/db_build.sql
  src/model/database/db_build_test.sql
  src/model/queries/postMemberInfo.js
  src/oauth.js
  src/test/db.test.js
Labels: awaiting-merge

#63 Verification of FAC github org membership
  package.json
  src/app.js
  src/controllers/error.js
  src/controllers/index.js
  src/oauth.js
Labels: awaiting-merge, testing needed

#65 Logout btn
  package-lock.json
  src/controllers/home.js
  src/views/layouts/main.hbs
  src/views/partials/footer.hbs
  src/views/partials/header.hbs
  src/views/partials/htmlHead.hbs
Labels: awaiting-merge

#66 Profile view complete
  package-lock.json
  src/controllers/index.js
  src/controllers/middleware.js
  src/controllers/profileDetails.js
  src/views/profileDetails.hbs
Labels: awaiting-merge

#67 add error handling
  src/controllers/error.js
  src/test/app.test.js
  src/views/error.hbs
Labels: awaiting-merge

#70 Worked on middleware, auth, userdata for handlebars
  src/controllers/index.js
  src/controllers/middleware.js
  src/controllers/profileDetails.js
Labels: awaiting-merge

#72 added hbs autopopulation, fixed logout button hbs conditional
  public/css/style.css
  src/views/partials/header.hbs
  src/views/profileDetails.hbs
Labels: in-review

#92 fix if/else branching in oauth checkOrgMembership function
  src/oauth.js
Labels: awaiting-merge, in-review

#91 update test names in test.js files for clarity when running tests
  src/test/app.test.js
  src/test/db.test.js
Labels: in-review

#83 More additions to profile page using handlebars
  package.json
  public/css/style.css
  public/dom/profile.js
  src/app.js
  src/controllers/auth.js
  src/controllers/error.js
  src/controllers/home.js
  src/controllers/index.js
  src/controllers/middleware.js
  src/controllers/profile.js
  src/controllers/profileDetails.js
  src/model/database/db_build.js
  src/test/app.test.js
  src/test/unit.test.js
  src/views/helpers/index.js
  src/views/helpers/jobPrefIsPublic.js
  src/views/helpers/jobStatusText.js
  src/views/home.hbs
  src/views/layouts/main.hbs
  src/views/partials/header.hbs
  src/views/partials/profile_jobDetails.hbs
  src/views/partials/profile_myDetails.hbs
  src/views/partials/profile_viewMode.hbs
  src/views/profile.hbs
Labels: in-review

#97 SQL query to get all members and basic information from db - Issue80
  src/model/database/db_build_test.sql
  src/model/queries/getAllMemberData.js
  src/test/db.test.js
Labels: awaiting-merge

#98 SaveJobDetails query
  src/controllers/index.js
  src/controllers/middleware.js
  src/controllers/profile.js
  src/model/database/db_build.sql
  src/model/database/db_build_test.sql
  src/model/queries/saveJobDetails.js
  src/test/app.test.js
  src/test/db.test.js
  src/test/unit.test.js
  src/views/helpers/compare.js
  src/views/helpers/index.js
  src/views/helpers/jobPrefIsPublic.js
  src/views/helpers/jobStatusText.js
  src/views/partials/profile_jobDetails.hbs
  src/views/partials/profile_myDetails.hbs
  src/views/partials/profile_viewMode.hbs
Labels: in-review

#96 Link front end details form with back end database
  src/controllers/home.js
  src/controllers/index.js
  src/controllers/profile.js
  src/lib/makeFacCodeName.js
  src/model/queries/addFacCodeReturnID.js
  src/model/queries/getAllFacCodes.js
  src/model/queries/getFacCodeID.js
  src/model/queries/index.js
  src/model/queries/postMemberInfo.js
  src/model/queries/saveJobDetails.js
  src/model/queries/saveProfileData.js
  src/model/queries/updateMemberDetails.js
  src/test/db.test.js
  src/test/unit.test.js
  src/views/helpers/index.js
Labels: awaiting-merge

#12 Add basic information to README.md
  README.md
Labels: in-review

#103 Add basic css styling based on style guide
  .gitignore
  public/css/style.css
  public/css/style.scss
  src/views/home.hbs
  src/views/partials/footer.hbs
  src/views/partials/header.hbs
  src/views/partials/htmlHead.hbs
  src/views/partials/profile_jobDetails.hbs
  src/views/partials/profile_myDetails.hbs
  src/views/partials/profile_viewMode.hbs
Labels: in-review

#108 Error handling + moving saveJobDetails to profile.js handler
  src/controllers/index.js
  src/controllers/middleware.js
  src/controllers/profile.js
  src/model/queries/getAllMemberData.js
  src/model/queries/postMemberInfo.js
  src/oauth.js
  src/test/app.test.js
  src/test/db.test.js
  src/views/partials/profile_jobDetails.hbs
  src/views/partials/profile_viewMode.hbs
Labels: awaiting-merge

#23 Add documentation on the design process (week one)
  Design Folder/journey.md
Labels: awaiting-merge

#134 127 api tech stack pull
  package-lock.json
  package.json
  src/lib/getGitHubStack.js
  src/test/api.test.js
  src/test/unit.test.js
Labels: in-review

#133 Issue120 - change account settings to delete account button
  public/dom/profile.js
  src/views/partials/profile_delete.hbs
  src/views/partials/profile_viewMode.hbs
  src/views/profile.hbs
Labels: awaiting-merge

#131 created card links and conditional display of edit btns/privacy info
  src/controllers/profile.js
  src/views/allmembers.hbs
  src/views/partials/profile_jobDetails.hbs
  src/views/partials/profile_viewMode.hbs
Labels: awaiting-merge

#132 Issue130 techstacksql
  src/model/database/db_build_test.sql
  src/model/queries/query_tech-stack.js
  src/test/db.test.js
Labels: awaiting-merge

#135 issue127 autosuggest stack
  src/lib/githubApiCalls.js
  src/oauth.js
  src/test/api.test.js
  src/test/unit.test.js
Labels: awaiting-merge

#138 security helmet added
  package-lock.json
  package.json
  src/app.js
Labels: awaiting-merge

#146 bug fix closes #142
  src/lib/githubApiCalls.js
  src/test/api.test.js
Labels: awaiting-merge

#141 Issue130 - SQL integrated queries to add member's tech stack
  src/lib/lowerCaseArray.js
  src/lib/removeArrayDuplicates.js
  src/model/queries/processMemberTechStack.js
  src/model/queries/queryDb_TechStackTables.js
  src/test/db.test.js
  src/test/unit.test.js
Labels: awaiting-merge

#140 add notmember-view
  src/controllers/index.js
  src/views/notmember.hbs
Labels: in-review

#144 add UNIQUE constrainst to github_id db schema field
  src/model/database/db_build.sql
  src/model/database/db_build_test.sql
Labels: in-review

#147 remove possible api rate limit causes
  src/app.js
  src/oauth.js
  src/test/api.test.js
  src/test/app.test.js
  src/test/db.test.js
Labels: in-progress, priority-1

#149 set up webpack
  .babelrc
  package-lock.json
  package.json
  public/css/style.css
  public/dom/home.js
  public/dom/index.js
  public/dom/profile.js
  src/static/css/style.scss
  src/static/dom/home.js
  src/static/dom/index.js
  src/static/dom/profile.js
  webpack.config.js
Labels: awaiting-merge

#152 Connected stack submission front-end and back-end
  package-lock.json
  public/dom/profile.js
  src/controllers/index.js
  src/controllers/profile.js
  src/model/queries/getMemberData.js
  src/model/queries/index.js
  src/model/queries/processMemberTechStack.js
  src/static/dom/profile.js
  src/test/db.test.js
  src/views/partials/profile_editJobDetails.hbs
  src/views/partials/profile_editMyDetails.hbs
  src/views/partials/profile_editTechStack.hbs
  src/views/partials/profile_viewMode.hbs
  src/views/profile.hbs
Labels: awaiting-merge

#150 modularise queries and subqueries
  src/model/queries/addFacCohortReturnID.js
  src/model/queries/getAllFacCohorts.js
  src/model/queries/getAllMemberData.js
  src/model/queries/getFacCohortID.js
  src/model/queries/getMemberData.js
  src/model/queries/index.js
  src/model/queries/processMemberTechStack.js
  src/model/queries/saveProfileData.js
  src/model/queries/subqueries/queryDbFacCohortTable.js
  src/model/queries/subqueries/queryDbTechStackTables.js
  src/model/queries/updateMemberDetails.js
  src/test/db.test.js
Labels: in-review

#159 replace anchor tags with event listeners on profile cards
  public/dom/allmembers.js
  src/static/dom/allmembers.js
  src/views/allmembers.hbs
  src/views/layouts/main.hbs
  webpack.config.js
Labels: awaiting-merge

#164 update readme
  README.md
  src/model/queries/processMemberTechStack.js
  src/test/db.test.js
Labels: in-review

#165 Add more styling to nodes
  public/css/style.css
  public/dom/profile.js
  src/static/css/style.scss
  src/static/dom/profile.js
  src/views/partials/profile_editTechStack.hbs
  src/views/partials/profile_stackDetails.hbs
  src/views/partials/profile_viewMode.hbs
  src/views/profile.hbs
Labels: awaiting-merge
